use libp2p::core::Endpoint;
use libp2p::core::transport::PortUse;
use libp2p::swarm::handler::ConnectionEvent;
use libp2p::swarm::{
    ConnectionDenied, ConnectionHandler, ConnectionHandlerEvent, ConnectionId, FromSwarm,
    NetworkBehaviour, SubstreamProtocol, THandler, THandlerInEvent, THandlerOutEvent, ToSwarm,
    handler,
};
use libp2p::{Multiaddr, PeerId, StreamProtocol};
use libp2p_core::upgrade::ReadyUpgrade;
use musig2::KeyAggContext;
use std::num::IntErrorKind::PosOverflow;
use std::task::{Context, Poll};

// client-server authentication
#[derive(Default)]
pub struct MusigBehaviour {
    n_parties: usize,
    events: std::collections::VecDeque<Event>,
}

/// Event generated by the `Ping` network behaviour.
#[derive(Debug)]
pub struct Event {
    /// The peer ID of the remote.
    pub peer: PeerId,
    /// The connection the ping was executed on.
    pub connection: ConnectionId,
    /// The result of an inbound or outbound ping.
    pub result: Result<Vec<u8>, super::Failure>,
}

pub const PROTOCOL_NAME: StreamProtocol = StreamProtocol::new("/libp2p/musig2/1.0.0");
impl NetworkBehaviour for MusigBehaviour {
    type ConnectionHandler = MusigHandler;
    type ToSwarm = Event;

    fn handle_established_inbound_connection(
        &mut self,
        _connection_id: ConnectionId,
        peer: PeerId,
        local_addr: &Multiaddr,
        remote_addr: &Multiaddr,
    ) -> Result<THandler<Self>, ConnectionDenied> {
        println!("connection in bound: {:?} {:?} {:?}", peer, local_addr, remote_addr);
        Ok(MusigHandler {})
    }

    fn handle_established_outbound_connection(
        &mut self,
        connection_id: ConnectionId,
        peer: PeerId,
        addr: &Multiaddr,
        role_override: Endpoint,
        port_use: PortUse,
    ) -> Result<THandler<Self>, ConnectionDenied> {
        println!("connection out bound: {:?} {:?} {:?}", connection_id, peer, addr);
        Ok(MusigHandler {})
    }

    fn on_swarm_event(&mut self, event: FromSwarm) {
        println!("musig on swarm event {:?}", event);
    }

    fn on_connection_handler_event(
        &mut self,
        peer: PeerId,
        connection: ConnectionId,
        result: THandlerOutEvent<Self>,
    ) {
        println!("musig on handler event {:?} {:?} {:?}", peer, connection, result);
        self.events.push_front(Event { peer, connection, result })
    }

    fn poll(
        &mut self,
        cx: &mut Context<'_>,
    ) -> Poll<ToSwarm<Self::ToSwarm, THandlerInEvent<Self>>> {
        if let Some(e) = self.events.pop_back() {
            Poll::Ready(ToSwarm::GenerateEvent(e))
        } else {
            Poll::Pending
        }
    }
}

pub struct MusigHandler {}

impl ConnectionHandler for MusigHandler {
    type FromBehaviour = std::convert::Infallible;
    type ToBehaviour = Result<Vec<u8>, super::Failure>;
    type InboundProtocol = ReadyUpgrade<StreamProtocol>;
    type OutboundProtocol = ReadyUpgrade<StreamProtocol>;
    type InboundOpenInfo = ();
    type OutboundOpenInfo = ();

    fn listen_protocol(&self) -> SubstreamProtocol<Self::InboundProtocol, Self::InboundOpenInfo> {
        println!("musig listening protocol");
        SubstreamProtocol::new(ReadyUpgrade::new(PROTOCOL_NAME), ())
    }

    fn poll(
        &mut self,
        cx: &mut Context<'_>,
    ) -> Poll<
        ConnectionHandlerEvent<Self::OutboundProtocol, Self::OutboundOpenInfo, Self::ToBehaviour>,
    > {
        println!("mulsig poll");
        Poll::Pending
    }

    fn on_behaviour_event(&mut self, _event: Self::FromBehaviour) {
        todo!()
    }

    fn on_connection_event(
        &mut self,
        event: ConnectionEvent<
            Self::InboundProtocol,
            Self::OutboundProtocol,
            Self::InboundOpenInfo,
            Self::OutboundOpenInfo,
        >,
    ) {
        println!("musig handler connection event: {:?}", event);
    }
}
