[package]
name = "consensus-light-client"
version.workspace = true
edition.workspace = true

[dependencies]
k256 = { version = "0.13.3", features = ["expose-field"] }
base64 = "0.21.7"
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"