name: Cargo Build & Test

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.*
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        timeout-minutes: 30
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        timeout-minutes: 30
        with:
          profile: minimal
          toolchain: nightly-2025-06-30
          override: true
      - name: Install Dependencies
        run: sudo apt update && sudo apt install protobuf-compiler
      - run: rustup component add clippy
      - run: cargo clippy --all-targets -- -D warnings
  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly-2025-06-30
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt update && sudo apt install protobuf-compiler
      - name: Launch the Regtest
        run: cd scripts && docker compose up -d
      - name: Run all unit tests
        run: cargo test -r --features tests
