name: Time-consuming test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          set -e
          export PATH=$HOME/.cargo/bin:$PATH
          cargo test -r e2e_take_1  --features tests --features e2e-tests
          cargo test -r e2e_take_2  --features tests --features e2e-tests
          cargo test -r e2e_disprove  --features tests --features e2e-tests
